### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by Ayushk4**
- [X] Update the Exec. to Adv and CTM to Exec.
- [X] Add the names of the new CTM
- [X] Add the pages for each CTM
- [X] Add projects
- [X] Hide the button to access terminal
- [X] Update events like git, ubuntu-fest, python workshop & KWoC

### CODE REVIEW

**Comment by Ayushk4** [comment]
@sangeet259 I am done with the updates can you guide me with the Travis build error.
Also, @thealphadollar Can you improve on the description for the new projects that I added, especially OnThisDay.

**Comment by thealphadollar** [comment]
@sangeet259 Can you please give me push rights to this repo?

**Comment by sangeet259** [comment]
Hey, I am traveling, I'll do that in a couple of hours.

On Nov 30, 2018 11:37, "Shivam Kumar Jha" <notifications@github.com> wrote:

@sangeet259 <https://github.com/sangeet259> Can you please give me push
rights to this repo?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kossiitkgp/kossiitkgp.github.io/pull/173#issuecomment-443101660>,
or mute the thread

**Comment by thealphadollar** [comment]
ping @sangeet259

**Comment by Ayushk4** [comment]
@dibyadas Can you give me and/or @thealphadollar pushing access to this repo?

**Comment by dibyadas** [comment]
Someone's already done it. You both have write access to it.

**Comment by sangeet259** [comment]
Hey, you and @thealphadollar have been given write access since yesterday.

**Review by thealphadollar — CHANGES_REQUESTED** [review]
Please fix the link errors shown by Travis :)

**Comment by sangeet259** [comment]
@americast can you look into this.

**Comment by thealphadollar** [comment]
@sangeet259 Travis is showing links of the  websites that can't be opened for some reason. We can easily remove this, there is no need of help from @americast

**Comment by sangeet259** [comment]
I am in a hospital. If this is not urgent I will look into them as I reach
hime by evening.

**Comment by americast** [comment]
Actually, we had a travis cron in place to automatically update the individual projects page of every member with pinned repos on their GitHub profile page. The same cron would also update the total no of contributions in the home page. That has been turned off since long. Hence the individual profile pages on the website are completely outdated and are hence throwing 404 errors. It's time we restart the cron. If not, we need to manually run the script once to update the pages.

**Comment by thealphadollar** [comment]
Merging this right away. I'll see if any errors are there after deployment.

**Pull request merged**
