### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by ashishkg0022**
Changed browser tab icon (favicon) to koss logo #11

### CODE REVIEW

**Review by americast — APPROVED** [review]
Looks good!

**Review by pranitbauva1997 — APPROVED** [review]
LGTM!

**Comment by americast** [comment]
@pranitbauva1997 May be a "squash and merge" would have been better here ?

**Comment by pranitbauva1997** [comment]
I usually like having a merge commit even for a very small change. Do you all usually "squash and merge" for small changes and have a merge commit for bigger changes?

**Comment by americast** [comment]
Yes! I guess it is better to avoid unnecessary merge commits for such small
changes. Also, when I merge PRs from a person who has admin access anyway,
I prefer to use "rebase and merge".



Gramercy,
Sayan Sinha.


*Contact info:*-
*Website:*   www.sayansinha.tk
*GitHub:*    @americast <http://www.github.com/americast>
*E-mail*:     sayan.sinha@iitkgp.ac.in

2017-05-03 20:06 GMT+05:30 Pranit Bauva <notifications@github.com>:

**Comment by pranitbauva1997** [comment]
Cool! Thanks for informing!

**Pull request merged**
