### PR TITLE
github poster changed

### PR DESCRIPTION
**Pull request by ankita132**

### CODE REVIEW

**Review by pranitbauva1997 — DISMISSED** [review]
LGTM! Thanks!

**Comment by americast** [comment]
@nitinkgp23 Can you confirm the date and the venue ? If not, I guess we could change those to "Coming Soon" and just "Vikramshila" respectively.

**Comment by nitinkgp23** [comment]
@americast Coming soon would be better. :)

**Review by americast — CHANGES_REQUESTED** [review]
Please update the time and venue with something uncertain.

**Pull request merged**
