### PR TITLE
description section added: event page

### PR DESCRIPTION
**Pull request by vernwalrahul**

### CODE REVIEW

**Review by americast — APPROVED** [review]
Looks good !

**Review by americast — CHANGES_REQUESTED** [review]
May be a fade in animation with `wow.js` for a row of tiles would make it look better ?

**Comment by pranitbauva1997** [comment]
I have some design ideas which can be implemented:

- Our whole color theme should be blue and not brown. Inconsistency makes the thing look bad.
- Typography doesn't seem appropriate.
- The borders of the block can be made smooth to have a better effect.
- The font type should be changed to something that is a little informal and be consistant with the font. The font in the other section of the website is different from this.

Right now the blocks are looking very "uptight" while they should be looking like "chill". This is maybe because you have preferred to use super straight lines and perfect rectangles.

**Review by pranitbauva1997 — APPROVED** [review]
@vernwalrahul Thanks for incorporating my changes. Now this looks really awesome!

**Review by americast — APPROVED** [review]

**Pull request merged**
