### PR TITLE
added events page

### PR DESCRIPTION
**Pull request by vernwalrahul**

### CODE REVIEW

**Comment by americast** [comment]
@vernwalrahul The KOSS logo has been added multiple times at different places. Could you link them to the one used for homepage ?

**Comment by vernwalrahul** [comment]
@americast Sure, I was just adding the help page. I will commit that too with these changes.

**Comment by pranitbauva1997** [comment]
Cleaning up the logos can be in a separate PR as well.

**Comment by pranitbauva1997** [comment]
When multiple people are working on setting up the initial stack, these things happen. The best is to not bring those up in the reviews. Initial setup should be review heavy since it is mainly done by trusted people. If you recognize some issues (like multiple logos) then open an issue and assign it to someone who isn't familiar with the code base. This is how you can involve others as well while you can work on the main stack.

**Review by americast — APPROVED** [review]

**Pull request merged**
