### PR TITLE
Add 404.html #140

### PR DESCRIPTION
**Pull request by SourangshuGhosh**
Respected Sir
Very Sorry for a new pull request. This is a continuation of the previous issue #140 .My earkier forked repo wasn't working and some of the folders got deleted, so I have to fork again and do some work. As per your request I am attaching the photo. I have added the KOSS footer and logo but coudn't find out the grammatical mistake part you are saying about.
IMG_20200715_213721

### CODE REVIEW

**Comment by xypnox** [comment]
Hi @SourangshuGhosh,

I really appreciate the enthusiasm with which you have attempted to fix the critical issue for the missing 404 page, and am excited to check out the changes. However, there are a few things that I would like to discuss first:

**A commit represents a unique change logically.** 

Now, What do we consider as a unique logical change? For example, adding a new file with the contents is a unique change. But remember the change should be unique and a single unit in itself. For example, in this PR, the changes could be adding a 404.html page. And then another could be adding a `.htaccess` file.

Take care that saving a file once doesn't constitute a unique change in itself. There can be several changes to a piece of code, you are invited to go ahead and make them, but keep them _local_ and do not commit every time you have made a slight change. We are patient and will wait for you to make the appropriate changes. 

If you do not want us to review the code _just now_ and are in progress of making the changes, change the type of the Pull request to "draft pull request". After you have made the changes that you want and are satisfied with the state of the PR, committed in logical block of changes, switch the type of Pull request from draft back to normal one so that it is ready for review.

Once again, I am glad that you have attempted to fix a critical bug and I will be patiently waiting for the PR to reach a status for review, till then please take care to commit a set of logical changes. Thanks!

PS: Also, it would be a good time to [git squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to combine the several commits.

**Comment by SourangshuGhosh** [comment]
I have changed the pull request to draft as you said to me. Can you give me some more suggestions regarding the changes I need to do in the fonts or style etc....

**Comment by SourangshuGhosh** [comment]
@rakaar  Is there improvement or suggestions regarding the changes I need to do in the fonts or style etc....

**Comment by rakaar** [comment]
Thanks a lot for fixing the bug @SourangshuGhosh 
Please don't forget these 2 important things 
1. Never send a PR from master branch, it is advisable to send from a branch with an appropriate name related to the task
2.  Squash your commits, when there are too many

Regarding (2) I am squashing and merging it myself

**Pull request merged**
