### PR TITLE
Revert "Revert "restore subheader""

### PR DESCRIPTION
**Pull request by americast**
Reverts kossiitkgp/kossiitkgp.github.io#85

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
What is happening over here guys?

**Comment by americast** [comment]
@dhiraj161298 reverted a PR without any comments, I guess by mistake, so here's the revert of the revert :stuck_out_tongue: !

**Comment by pranitbauva1997** [comment]
This is bullshit and will not be tolerated. If he did it by mistake then ask him whether it was a mistake or not. If you continue this kind of shitty things, I am taking away both of your write access.

**Comment by americast** [comment]
@pranitbauva1997 I have absolutely no idea why this happened. From my side, I am never going to revert a PR without informing why I am doing so, **never ever**.

**Comment by americast** [comment]
It's not that I am against PR reversals, but I demand an explanation from @dhiraj161298 why he did not comment why he was reverting the PR.

**Comment by djbarnwal** [comment]
@americast In my initial layout PR #54 I added some content on the homepage which you later removed without any reason with one of your PRs. Yesterday in my another PR I restored it along with many other changes. @americast then did a restore header PR #84 without consulting me about it. I wrote a comment why this isn't the right way to go [here ](https://github.com/kossiitkgp/kossiitkgp.github.io/pull/84#issuecomment-301242283 ) and reverted it. I don't know what happened to @americast after that, he ignored my comment and reverted my revert.

**Comment by OrkoHunter** [comment]
Hey guys @dhiraj161298 @americast and co, do guys have an active chat/mail or any other communication platform you use for the website development? It would really help you. You are free to use the #website channel on slack. Things like, "I have pushed another update, everyone please rebase", or "@someone Please test out this branch for me" keeps everyone in sync and doesn't lead to unpleasing mishaps.

**Comment by americast** [comment]
@dhiraj161298 :pray: 

Calm down man :smile: ! I thought your clone was not updated and you worked on an older version. I missed out on the comment you had made in the closed PR. I request you to kindly make comments in the new PRs so it's easy to remain in sync. Alternately, you could use the #website channel on slack as mentioned by @OrkoHunter.

**Pull request merged**
