### PR TITLE
metatags added

### PR DESCRIPTION
**Pull request by harishnandan**
description of pages other than homepage will be added after completion of the respective pages.

### CODE REVIEW

**Review by pranitbauva1997 — APPROVED** [review]
LGTM! :-)

**Review by americast — CHANGES_REQUESTED** [review]
I guess we could have the meta tags in one file. We could import the same in all the other files.

**Comment by harishnandan** [comment]
As every page will have its own meta tags ,which needs to be changed after the completion of the page,.it is unnecessary to import them from a external file. It is better that the keywords and description is there on the html file only.

**Review by americast — APPROVED** [review]
@harishnandan Cool!

**Pull request merged**
