### PR TITLE
Add About Us page

### LINKED ISSUE #76: Addition of rough content
Rough content needs to be added at every page so that anyone willing to add content is easily able to find a place for it.

### PR DESCRIPTION
**Pull request by americast**
Fixes #76.

### CODE REVIEW

**Review by pranitbauva1997 — CHANGES_REQUESTED** [review]
Except for font size which needs to be reduced, everything is looking fine.

**Comment by pranitbauva1997** [comment]
The title of the web page says "Our Team" while the menu button is corresponding to "about us" and finally the page is having both. Frankly, I am not sure what to write where, but I do hope it has come to your notice before and you have done this purposely. Having a justification here would be better.

**Comment by pranitbauva1997** [comment]
I was using `Inspect Element` and the font size came up to be `1.33em`. On changing it to `1.10em` it is looking much better.

2017-05-11-123359_1366x768_scrot

**Comment by americast** [comment]
@pranitbauva1997 Thanx a lot for pointing out the error and suggesting fixes! I have tried incorporating them in the last commit.

**Review by pranitbauva1997 — APPROVED** [review]

**Comment by pranitbauva1997** [comment]
Looks much better now! Can be merged! :-)

**Pull request merged**
