### PR TITLE
Fixed profile page and card for @mianto

### PR DESCRIPTION
**Pull request by dibyadas**
The JSON file containing user ID was taken from bhattu's repo, where @Mianto Slack ID is `@minato`. Which caused the wrong profile page to be generated.

### CODE REVIEW

**Comment by dibyadas** [comment]
Closes #135

**Comment by americast** [comment]
@dibyadas Cool! But wouldn't it be better if we mention `@Minato` in place of `@minato` even in the `About Us` and profile page ? 

ping @Mianto

**Comment by dibyadas** [comment]
@americast  You mean `@Mianto` and not `@mianto` ?

**Comment by americast** [comment]
@dibyadas Yeah! :+1:

**Comment by americast** [comment]
@dibyadas Also, the travis build is failing (https://travis-ci.org/kossiitkgp/kossiitkgp.github.io) due to five missing links, all originating from the profiles. May be regenerating for these members would help. Can you please have a look ?

**Comment by dibyadas** [comment]
@americast I noticed that as well. I will have a look at it soon.

**Comment by dibyadas** [comment]
@americast `@bad-smruti`'s blog link is a linkedin url. And there is some issue regarding that. See here :- https://github.com/gjtorikian/html-proofer/issues/215 . It seems Linkedin has some issues with their links being checked. A fix would be to ignore the 999 error by adding this `http_status_ignore: [999]` in the options. What do you think?

**Comment by americast** [comment]
@dibyadas I've fixed it as per your request in PR #138

**Comment by americast** [comment]
@dibyadas Do you think it would be better to specifically ignore LinkedIn URLs instead of ignoring HTTP status 999 ?

**Comment by dibyadas** [comment]
@americast I'm not really sure about that. This is just one case. I do not think this will be much of a problem. Now that you have fixed that, I will trigger a build in travis.

**Review by americast — APPROVED** [review]
Thanx @dibyadas ! :+1:

**Pull request merged**
