### PR TITLE
removed the help tab

### PR DESCRIPTION
**Pull request by ankita132**

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
Um. I think you have created this branch from your previous PR. Please rebase this on the current master.

**Review by pranitbauva1997 — CHANGES_REQUESTED** [review]
Except for rebasing, other things look good!

**Comment by ankita132** [comment]
rebased.

**Review by pranitbauva1997 — APPROVED** [review]

**Comment by pranitbauva1997** [comment]
LGTM! :-) Can be merged!

**Pull request merged**
