### PR TITLE
index: remove redundant things

### PR DESCRIPTION
**Pull request by pranitbauva1997**
We shall never use "Terms and Conditions" and "Privacy Policy" thus it makes sense to remove it altogether

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
Ah! This change is not complete. I think I would need to remove this from every individual file.

I guess this tells us that we should probably use a html file just for footer and import it to others.

**Comment by americast** [comment]
@pranitbauva1997 I have updated the PR with a commit which changes this for other pages as well.

**Comment by pranitbauva1997** [comment]
@americast Thanks! This problem tells us that we are doing something wrong which should be fixed ASAP.  Please do not merge this right now. Let's reorganize the source code and make it modular. See the issue I opened #20

**Review by americast — COMMENTED** [review]
Waiting for a fix for #20

**Comment by americast** [comment]
@pranitbauva1997 Could you kindly resolve the conflicts ?

**Review by americast — DISMISSED** [review]
Projects page overridden by events.

**Review by americast — APPROVED** [review]
Looks good! Thanks @pranitbauva1997 :slightly_smiling_face: !

**Pull request merged**
