### PR TITLE
Sample profile

### PR DESCRIPTION
**Pull request by americast**
Addition of a sample profile page. Please suggest edits.

It has been deployed at: https://kossdev-pr-30.herokuapp.com/profiles/index.html

### CODE REVIEW

**Review by pranitbauva1997 — DISMISSED** [review]
LGTM! :-)

**Comment by djbarnwal** [comment]
Can you please remove those flashy arrows? Add more padding between the Project name and description. It would also be great if you could change the Project's Name font size and make it bigger.

In case you want to add social icons, semantics has inbuilt icons pack.
Add Margin below the two buttons. Pack the user details such as social links, image, title etc. under one div and align it with the top bar. Refrain using br tags.

**Comment by dibyadas** [comment]
@americast This looks good! A little bit of changes here and there are required I think.

**Comment by rava-dosa** [comment]
Having a clean web page like of medium.com with this feature https://codyhouse.co/demo/morphing-modal-window/index.html#0

**Comment by americast** [comment]
@pranitbauva1997 @dhiraj161298 @dibyadas Updated the PR, please have a look.

**Pull request closed without merging**
