### PR TITLE
About us page updated for all members

### PR DESCRIPTION
**Pull request by dibyadas**
Also, fixed a small typo in the profile pages.
I have added the cards for each members in the about us page, by generating them automatically using the backend.
But many members have not even mentioned their name or updated their photo in their github profile.
Members who haven't done this are requested to update these .
The page can be seen at :- https://kossdev-pr-127.herokuapp.com/about/index.html

### CODE REVIEW

**Comment by dibyadas** [comment]
@americast Can you deploy an app for this PR?

**Comment by americast** [comment]
Done @dibyadas

**Comment by dibyadas** [comment]
@americast You can squash merge it in if this looks good. Have it reviewed by someone.

**Comment by djbarnwal** [comment]
@dibyadas This looks good

**Pull request merged**
