### PR TITLE
added the background image of about and project page

### LINKED ISSUE #112: New background images
The following pages need new background images : -

- [ ]  About Us
- [ ] Projects
- [x] Contact Us

### PR DESCRIPTION
**Pull request by ankita132**
fixes #112

### CODE REVIEW

**Review by americast — CHANGES_REQUESTED** [review]
@ankita132 This deletes quite a few event files. Kindly rebase with master.

**Comment by ankita132** [comment]
@americast i deleted them intentionally..there were two html files of makerparty and android workshop

**Comment by americast** [comment]
@ankita132 Cool! But do make sure you mention such edits in comments. :slightly_smiling_face:

**Review by americast — CHANGES_REQUESTED** [review]
The background image of the `About Us` page is not looking good. Could you kindly update it ? There's a minor camouflage of the text with the image.
Also, please update your system date and time.

**Comment by ankita132** [comment]
will take care of it next time

**Pull request merged**
